/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Comment } from '../model/comment';
import { GridFSBucketReadStream } from '../model/gridFSBucketReadStream';
import { InlineResponse400 } from '../model/inlineResponse400';
import { Model088b132e87cf3e85f7e7b } from '../model/model088b132e87cf3e85f7e7b';
import { NgReportsAttachmentImage } from '../model/ngReportsAttachmentImage';
import { NgReportsAuthUserPartial } from '../model/ngReportsAuthUserPartial';
import { NgReportsEnvironment } from '../model/ngReportsEnvironment';
import { NgReportsLogBase } from '../model/ngReportsLogBase';
import { Report } from '../model/report';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ReportsService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param body 
     * @param reportId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsControllerChangeFixed(body: boolean, reportId: string, observe?: 'body', reportProgress?: boolean): Observable<Report>;
    public reportsControllerChangeFixed(body: boolean, reportId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Report>>;
    public reportsControllerChangeFixed(body: boolean, reportId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Report>>;
    public reportsControllerChangeFixed(body: boolean, reportId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling reportsControllerChangeFixed.');
        }

        if (reportId === null || reportId === undefined) {
            throw new Error('Required parameter reportId was null or undefined when calling reportsControllerChangeFixed.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Report>('put',`${this.basePath}/reports/fixed/${encodeURIComponent(String(reportId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param reportId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsControllerChangeSeverity(body: number, reportId: string, observe?: 'body', reportProgress?: boolean): Observable<Report>;
    public reportsControllerChangeSeverity(body: number, reportId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Report>>;
    public reportsControllerChangeSeverity(body: number, reportId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Report>>;
    public reportsControllerChangeSeverity(body: number, reportId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling reportsControllerChangeSeverity.');
        }

        if (reportId === null || reportId === undefined) {
            throw new Error('Required parameter reportId was null or undefined when calling reportsControllerChangeSeverity.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Report>('put',`${this.basePath}/reports/severity/${encodeURIComponent(String(reportId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param dataIsFromAuthService 
     * @param user 
     * @param title 
     * @param details 
     * @param logs 
     * @param formData 
     * @param attachments 
     * @param environment 
     * @param timestamp 
     * @param severity 
     * @param summary 
     * @param fixed 
     * @param comments 
     * @param environmentId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsControllerCreateForm(dataIsFromAuthService: boolean, user: NgReportsAuthUserPartial, title: string, details: string, logs: Array<NgReportsLogBase>, formData: any, attachments: Array<NgReportsAttachmentImage>, environment: NgReportsEnvironment, timestamp: number, severity: number, summary: string, fixed: boolean, comments: Array<Array<Comment>>, environmentId: string, observe?: 'body', reportProgress?: boolean): Observable<Report>;
    public reportsControllerCreateForm(dataIsFromAuthService: boolean, user: NgReportsAuthUserPartial, title: string, details: string, logs: Array<NgReportsLogBase>, formData: any, attachments: Array<NgReportsAttachmentImage>, environment: NgReportsEnvironment, timestamp: number, severity: number, summary: string, fixed: boolean, comments: Array<Array<Comment>>, environmentId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Report>>;
    public reportsControllerCreateForm(dataIsFromAuthService: boolean, user: NgReportsAuthUserPartial, title: string, details: string, logs: Array<NgReportsLogBase>, formData: any, attachments: Array<NgReportsAttachmentImage>, environment: NgReportsEnvironment, timestamp: number, severity: number, summary: string, fixed: boolean, comments: Array<Array<Comment>>, environmentId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Report>>;
    public reportsControllerCreateForm(dataIsFromAuthService: boolean, user: NgReportsAuthUserPartial, title: string, details: string, logs: Array<NgReportsLogBase>, formData: any, attachments: Array<NgReportsAttachmentImage>, environment: NgReportsEnvironment, timestamp: number, severity: number, summary: string, fixed: boolean, comments: Array<Array<Comment>>, environmentId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (dataIsFromAuthService === null || dataIsFromAuthService === undefined) {
            throw new Error('Required parameter dataIsFromAuthService was null or undefined when calling reportsControllerCreate.');
        }

        if (user === null || user === undefined) {
            throw new Error('Required parameter user was null or undefined when calling reportsControllerCreate.');
        }

        if (title === null || title === undefined) {
            throw new Error('Required parameter title was null or undefined when calling reportsControllerCreate.');
        }

        if (details === null || details === undefined) {
            throw new Error('Required parameter details was null or undefined when calling reportsControllerCreate.');
        }

        if (logs === null || logs === undefined) {
            throw new Error('Required parameter logs was null or undefined when calling reportsControllerCreate.');
        }

        if (formData === null || formData === undefined) {
            throw new Error('Required parameter formData was null or undefined when calling reportsControllerCreate.');
        }

        if (attachments === null || attachments === undefined) {
            throw new Error('Required parameter attachments was null or undefined when calling reportsControllerCreate.');
        }

        if (environment === null || environment === undefined) {
            throw new Error('Required parameter environment was null or undefined when calling reportsControllerCreate.');
        }

        if (timestamp === null || timestamp === undefined) {
            throw new Error('Required parameter timestamp was null or undefined when calling reportsControllerCreate.');
        }

        if (severity === null || severity === undefined) {
            throw new Error('Required parameter severity was null or undefined when calling reportsControllerCreate.');
        }

        if (summary === null || summary === undefined) {
            throw new Error('Required parameter summary was null or undefined when calling reportsControllerCreate.');
        }

        if (fixed === null || fixed === undefined) {
            throw new Error('Required parameter fixed was null or undefined when calling reportsControllerCreate.');
        }

        if (comments === null || comments === undefined) {
            throw new Error('Required parameter comments was null or undefined when calling reportsControllerCreate.');
        }

        if (environmentId === null || environmentId === undefined) {
            throw new Error('Required parameter environmentId was null or undefined when calling reportsControllerCreate.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (environmentId !== undefined && environmentId !== null) {
            queryParameters = queryParameters.set('environmentId', <any>environmentId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (dataIsFromAuthService !== undefined) {
            formParams = formParams.append('dataIsFromAuthService', <any>dataIsFromAuthService) as any || formParams;
        }
        if (user !== undefined) {
            formParams = formParams.append('user', <any>user) as any || formParams;
        }
        if (title !== undefined) {
            formParams = formParams.append('title', <any>title) as any || formParams;
        }
        if (details !== undefined) {
            formParams = formParams.append('details', <any>details) as any || formParams;
        }
        if (logs) {
            logs.forEach((element) => {
                formParams = formParams.append('logs', <any>element) as any || formParams;
            })
        }
        if (formData !== undefined) {
            formParams = formParams.append('formData', <any>formData) as any || formParams;
        }
        if (attachments) {
            attachments.forEach((element) => {
                formParams = formParams.append('attachments', <any>element) as any || formParams;
            })
        }
        if (environment !== undefined) {
            formParams = formParams.append('environment', <any>environment) as any || formParams;
        }
        if (timestamp !== undefined) {
            formParams = formParams.append('timestamp', <any>timestamp) as any || formParams;
        }
        if (severity !== undefined) {
            formParams = formParams.append('severity', <any>severity) as any || formParams;
        }
        if (summary !== undefined) {
            formParams = formParams.append('summary', <any>summary) as any || formParams;
        }
        if (fixed !== undefined) {
            formParams = formParams.append('fixed', <any>fixed) as any || formParams;
        }
        if (comments) {
            comments.forEach((element) => {
                formParams = formParams.append('comments', <any>element) as any || formParams;
            })
        }

        return this.httpClient.request<Report>('post',`${this.basePath}/reports`,
            {
                body: convertFormParamsToString ? formParams.toString() : formParams,
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param environmentId 
     * @param filter 
     * @param limit 
     * @param skip 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsControllerFindAll(environmentId: string, filter?: string, limit?: number, skip?: number, observe?: 'body', reportProgress?: boolean): Observable<Model088b132e87cf3e85f7e7b>;
    public reportsControllerFindAll(environmentId: string, filter?: string, limit?: number, skip?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Model088b132e87cf3e85f7e7b>>;
    public reportsControllerFindAll(environmentId: string, filter?: string, limit?: number, skip?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Model088b132e87cf3e85f7e7b>>;
    public reportsControllerFindAll(environmentId: string, filter?: string, limit?: number, skip?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (environmentId === null || environmentId === undefined) {
            throw new Error('Required parameter environmentId was null or undefined when calling reportsControllerFindAll.');
        }




        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (environmentId !== undefined && environmentId !== null) {
            queryParameters = queryParameters.set('environmentId', <any>environmentId);
        }
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('filter', <any>filter);
        }
        if (limit !== undefined && limit !== null) {
            queryParameters = queryParameters.set('limit', <any>limit);
        }
        if (skip !== undefined && skip !== null) {
            queryParameters = queryParameters.set('skip', <any>skip);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Model088b132e87cf3e85f7e7b>('get',`${this.basePath}/reports`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param reportId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsControllerFindOne(reportId: string, observe?: 'body', reportProgress?: boolean): Observable<Report>;
    public reportsControllerFindOne(reportId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Report>>;
    public reportsControllerFindOne(reportId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Report>>;
    public reportsControllerFindOne(reportId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (reportId === null || reportId === undefined) {
            throw new Error('Required parameter reportId was null or undefined when calling reportsControllerFindOne.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Report>('get',`${this.basePath}/reports/${encodeURIComponent(String(reportId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param attachmentId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsControllerReadStream(attachmentId: string, observe?: 'body', reportProgress?: boolean): Observable<GridFSBucketReadStream>;
    public reportsControllerReadStream(attachmentId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<GridFSBucketReadStream>>;
    public reportsControllerReadStream(attachmentId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<GridFSBucketReadStream>>;
    public reportsControllerReadStream(attachmentId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (attachmentId === null || attachmentId === undefined) {
            throw new Error('Required parameter attachmentId was null or undefined when calling reportsControllerReadStream.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<GridFSBucketReadStream>('get',`${this.basePath}/reports/attachments/${encodeURIComponent(String(attachmentId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param reportId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsControllerRemove(reportId: string, observe?: 'body', reportProgress?: boolean): Observable<Report>;
    public reportsControllerRemove(reportId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Report>>;
    public reportsControllerRemove(reportId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Report>>;
    public reportsControllerRemove(reportId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (reportId === null || reportId === undefined) {
            throw new Error('Required parameter reportId was null or undefined when calling reportsControllerRemove.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Report>('delete',`${this.basePath}/reports/${encodeURIComponent(String(reportId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param body 
     * @param reportId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public reportsControllerUpdate(body: Report, reportId: string, observe?: 'body', reportProgress?: boolean): Observable<Report>;
    public reportsControllerUpdate(body: Report, reportId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Report>>;
    public reportsControllerUpdate(body: Report, reportId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Report>>;
    public reportsControllerUpdate(body: Report, reportId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling reportsControllerUpdate.');
        }

        if (reportId === null || reportId === undefined) {
            throw new Error('Required parameter reportId was null or undefined when calling reportsControllerUpdate.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<Report>('put',`${this.basePath}/reports/${encodeURIComponent(String(reportId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
