/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { InlineResponse400 } from '../model/inlineResponse400';
import { Statistics } from '../model/statistics';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class StatisticsService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param sampling 
     * @param dateFrom 
     * @param dateTo 
     * @param projectId 
     * @param environmentId 
     * @param textFilter 
     * @param severity 
     * @param fixed 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public statisticsControllerGetStatistics(sampling: string, dateFrom: Date, dateTo: Date, projectId?: string, environmentId?: string, textFilter?: string, severity?: number, fixed?: boolean, observe?: 'body', reportProgress?: boolean): Observable<Statistics>;
    public statisticsControllerGetStatistics(sampling: string, dateFrom: Date, dateTo: Date, projectId?: string, environmentId?: string, textFilter?: string, severity?: number, fixed?: boolean, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Statistics>>;
    public statisticsControllerGetStatistics(sampling: string, dateFrom: Date, dateTo: Date, projectId?: string, environmentId?: string, textFilter?: string, severity?: number, fixed?: boolean, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Statistics>>;
    public statisticsControllerGetStatistics(sampling: string, dateFrom: Date, dateTo: Date, projectId?: string, environmentId?: string, textFilter?: string, severity?: number, fixed?: boolean, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sampling === null || sampling === undefined) {
            throw new Error('Required parameter sampling was null or undefined when calling statisticsControllerGetStatistics.');
        }

        if (dateFrom === null || dateFrom === undefined) {
            throw new Error('Required parameter dateFrom was null or undefined when calling statisticsControllerGetStatistics.');
        }

        if (dateTo === null || dateTo === undefined) {
            throw new Error('Required parameter dateTo was null or undefined when calling statisticsControllerGetStatistics.');
        }






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (sampling !== undefined && sampling !== null) {
            queryParameters = queryParameters.set('sampling', <any>sampling);
        }
        if (dateFrom !== undefined && dateFrom !== null) {
            queryParameters = queryParameters.set('dateFrom', <any>dateFrom.toISOString());
        }
        if (dateTo !== undefined && dateTo !== null) {
            queryParameters = queryParameters.set('dateTo', <any>dateTo.toISOString());
        }
        if (projectId !== undefined && projectId !== null) {
            queryParameters = queryParameters.set('projectId', <any>projectId);
        }
        if (environmentId !== undefined && environmentId !== null) {
            queryParameters = queryParameters.set('environmentId', <any>environmentId);
        }
        if (textFilter !== undefined && textFilter !== null) {
            queryParameters = queryParameters.set('textFilter', <any>textFilter);
        }
        if (severity !== undefined && severity !== null) {
            queryParameters = queryParameters.set('severity', <any>severity);
        }
        if (fixed !== undefined && fixed !== null) {
            queryParameters = queryParameters.set('fixed', <any>fixed);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Statistics>('get',`${this.basePath}/statistics`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
