/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {UserMini} from './userMini';

export interface Cd27b9e7dfa182c915462 {
  items: Array<UserMini>;
  totalItemsCount: number;
}
