/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Environment} from './environment';

export interface E86969db7b9aca4661ee5 {
  items: Array<Environment>;
  totalItemsCount: number;
}
