/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserMini } from './userMini';

export interface Model2769564a05589cc671a5a { 
    items: Array<UserMini>;
    totalItemsCount: number;
}