/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Report } from './report';

export interface Model2d1bdd334e0436ece64fd { 
    items: Array<Report>;
    totalItemsCount: number;
}