/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Project} from './project';

export interface Model46200d129e8b02714c63d {
  items: Array<Project>;
  totalItemsCount: number;
}
