/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Comment} from './comment';

export interface Model1ee5c5c7d8c6a5cdbbd6d {
  items: Array<Comment>;
  totalItemsCount: number;
}
