/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Report } from './report';

export interface Model458d5dc95861976d70324 { 
    items: Array<Report>;
    totalItemsCount: number;
}