/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Environment} from './environment';

export interface Model74f645d0a33a73be87ab4 {
  items: Array<Environment>;
  totalItemsCount: number;
}
