/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Report} from './report';

export interface Model088b132e87cf3e85f7e7b {
  items: Array<Report>;
  totalItemsCount: number;
}
