/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface StatisticsSample {
  /**
   * Parsed date
   */
  label: string;
  /**
   * Number of reports
   */
  value: number;
}
