/**
 * NgReports
 * NG Reports API
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserView {
  username: string;
  name: string;
  description: string;
  role: UserView.RoleEnum;
  createDate: Date;
  isActive: boolean;
}

export namespace UserView {
  export type RoleEnum = 0 | 1 | 2 | 3;
  export const RoleEnum = {
    NUMBER_0: 0 as RoleEnum,
    NUMBER_1: 1 as RoleEnum,
    NUMBER_2: 2 as RoleEnum,
    NUMBER_3: 3 as RoleEnum
  };
}
